<?php

namespace Command;

use Command\Abstraction\CommandInterface;

/**
 * Class CommandQueue
 *
 * @package GooglePosta\Command
 *
 * @method CommandInterface offsetGet($index)
 * @method CommandInterface current()
 */
class CommandQueue extends \ArrayIterator implements CommandInterface
{
    /**
     * @inheritdoc
     */
    public function __construct(array $array = array(), $flags = 0)
    {
        parent::__construct($array, $flags); // TODO: Change the autogenerated stub
    }

    /**
     * Execute the command
     *
     * @return CommandInterface
     */
    public function execute()
    {
        for ($this->rewind(); $this->valid(); $this->next()) {
            $command = $this->current();

            if (!($command instanceof CommandInterface)) {
                continue;
            }

            $command->execute();
        }
    }
}
